### ISSUE TITLE
✨ 배포 준비

### ISSUE THREAD

**Issue by sojeong0302** [sojeong0302/ImpoliteChatbot#15]
## TYPE
- [x] 새로운 기능 추가✨

## Description
배포 준비

## Todo
- [x] 페이지 제목 수정
- [x] Favicon 수정
- [x] 오픈 그래프 태그 설정

## ETC
x

## Period
2024.08.22 ~ 2024.08.22
